### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by lbartoletti**
Various fixes, thanks to clang.

There are others that can follow, but I prefer to do it step by step.

Also, would it be possible to have a standard code formatting? :)

### CODE REVIEW

**Comment by olevole** [comment]
Many thanks! I couldn't find the time to fix these warnings myself. 
As for formatting, you mean 'style(9)' for C ?

**Comment by mekanix** [comment]
I personally prefer clang-format because it has really nice integration with (neo)vim, and probably other IDE-alike editors out there.

**Comment by olevole** [comment]
@mekanix @lbartoletti in any case, any formatting will not hurt. Most of it was very quickly written code. Thanks a lot for taking this on!  

ps: now I will try to translate quantity into quality myself - I will write regression autotests for CBSD

**Comment by lbartoletti** [comment]
+1 for clang-format. Maybe, we can use the one from FreeBSD https://github.com/freebsd/freebsd-src/blob/main/.clang-format?

**Comment by lbartoletti** [comment]
@mekanix @olevole FYI, the result of my hardcore clang-tidy:

```
run-clang-tidy13 -clang-tidy-binary clang-tidy13 -clang-apply-replacements-binary clang-apply-replacements13 -checks="-*,clang-analyzer-*,cert-*,bugprone-*,misc-*,modernize-*,performance-*,portability-*,readability-*,-header-filter=.*" > tidy.log
clang-tidy-html tidy.log
```
https://lbartoletti.github.io/clang.html

**Comment by olevole** [comment]
i will add to CI it soon, thanks!

**Pull request merged**
