### PR TITLE
Update base jail

### PR DESCRIPTION
**Pull request by mekanix**

### CODE REVIEW

**Comment by mekanix** [comment]
I know args should be mandatory, for start, but I would like us to have some code to discuss before I deal with this subject fully

**Comment by olevole** [comment]
This script repeats the functional of https://github.com/cbsd/cbsd/blob/master/system/upgrade ( this is a modified version of freebsd-update script ). I do not remember why this script was created ;-(. Anyway, 'cbsd upgrade' doesn't support HardenedBSD platform. 

1)  If this script works on HBSD platform we do unnecessary operations with mktemp and config file for freebsd-update. it would be nice to generate this in function and call it before 

> FBSD_UPDATE="freebsd-update -f ${update_conf} -b ${basepath} --not-running-from-cron"



2) Just a suggestion: It seems that the configuration file has some parameters that can be changed in time. How about  make config file for this script, for example: /usr/local/cbsd/etc/defaults/baseupdate.conf with following content:

```
keyprint="800651ef4b4c71c27e60786d7b487188970f4b4169cc055784e21eb71d410cc5"
servername="update.FreeBSD.org"
components="world"

```

And after read this settings after

> init $*

via:

`readconf baseupdate.conf`

?

And use variables in config:

```
cat << EOF > "${update_conf}"
KeyPrint ${keyprint}
ServerName ${servername}
...

```
CBSD **readconf** function works in this way (in this order):

- read _$workdir/etc/defaults/<file>_, if file exist
- read _$workdir/etc/<file>_, if file exist

this allows CBSD users overwrite any 'default' settings. This schema inherited ideas from FreeBSD with /etc/defaults/* and /etc dirs


3) And a few cosmetic wishes:

a) Try to use the full path to the commands (use `which <cmd>`  ):

`/bin/rm ..`

instead of

`rm`

`/usr/bin/mktemp`

instead of

`mktemp`

this is due to behavior of /usr/local/bin/cbsd interpreter which first looks for commands in $workdir hier.
In the future CBSD versions all full-path command will be changed to variables like RM_CMD, MKTEMP_CMD, where the value of the variables will depend on platform ( Open/Dragon/HardenedBSD ).

b) For CBSD code style, for subshell command use $(  ) , instead of ` `:

-- update_conf=`mktemp`
++ update_conf=$( /usr/bin/mktemp )

b) Good programming style when you use mktemp for temporary file is applying 'trap'

Instead of:
```
test=$( /usr/bin/mktemp )
.... //work with $test
/bin/rm -f ${test}
```

use:

```
test=$( /usr/bin/mktemp )
trap "/bin/rm -f ${test}" HUP INT ABRT BUS TERM EXIT
.... //work with $test
```

"HUP INT ABRT BUS TERM EXIT" - is signal list (man signal) which trap is handled.
You can use 'trap' for any 'cleanup/post-execution' action. 

Except this - if your script suddenly dies (or will be interrupted by kill, Ctrl+C, segfault ..), your last line (with rm for cleanup temp file) will not work, while trap always work.

**Comment by olevole** [comment]
And another "cosmetic wishes:"

use

```
if [ "${platform}" = "DragonFly" ]; then
  hbsd-update -r
  ..
fi

if [ "${platform}" = "FreeBSDFl" ]; then
   freebsd-update -f
   ...
fi
```

or

```
case "${platform}" in
    DragonFly*)
           hbsd-update -r
           ;;
     FreeBSD*)
           freebsd-update -f
           ;;
esac
```

instead of checking platform-specific commands - this is already done via cbsd.conf which always works when interpreter is #!/usr/local/bin/cbsd

**Comment by mekanix** [comment]
`cbsd upgrade` doesn't call freebsd-update anywhere so I suppose a lot from `cbsd upgrade` is now in `freebsd-update`? If yes, I'll leave it that way not to break some compatibility and continue working on `cbsd baseupdate`.

About your comments, I totally agree, I just wanted to present the idea first, before I start properly dealing with the script. Thanx for mentoring :o)

**Comment by olevole** [comment]
Old uprade script was based on freebsd-update. It seems there is no reason to leave it. Moreover, your new implementation is support of several platforms. In this way, if execution freebsd-update in new method work fine baseupdate supersede old script

**Comment by mekanix** [comment]
I think I fixed everything according to your comments, and I removed any arguments, as running the script should update all jails. If needed, we can limit it later with args.

**Comment by olevole** [comment]
Cool! Please add new changes first to the **develop** branch the next time. Our git workflow - we work in the **develop** branch and on readiness and testing, we do merge to master branch. 

BTW: If you want a new command to be available in `cbsd help`, you need to add this command into https://github.com/cbsd/cbsd/blob/develop/securecmd ( sorted command list )

Thanks you!

**Comment by mekanix** [comment]
I did branch out develop, but pull request defaults to master. Can we make develop main branch or something? It's really stupid to have mistakes like this.

Thanx for the `cbsd help`, I'll keep it hidden for now, to test it more (with Reggae and outside of it). I want it stable in .18

**Comment by olevole** [comment]
Hmm, really - I did not know about the setup for 'default branch' before. GitHub allow to setup this. Well, I did it. Thanks!

**Pull request merged**
