### PR TITLE
Revert to old exec if no LOGIN_STR

### PR DESCRIPTION
**Pull request by mekanix**

### CODE REVIEW

**Comment by mekanix** [comment]
Without this PR `cbsd jexec` never executes the command

**Comment by olevole** [comment]
@mekanix Can you remind me what the problem is with the current version? It seems like once we fixed it once. The version you are offering is also incorrect, see: https://github.com/cbsd/cbsd/issues/470

I need to take a timeout, there should be a third option

**Comment by mekanix** [comment]
I'll obviously have to research more. With current version nothing happens, as if command was never executed.

**Comment by mekanix** [comment]
I think the problem is input. For example, this works:
```
/usr/bin/nice -n 0 /usr/sbin/jexec -U root 2 /bin/sh <<CBSD_EOF
id
CBSD_EOF
```
but this doesn't
```
/usr/bin/nice -n 0 /usr/sbin/jexec -U root 2 /bin/sh <<CBSD_EOF
read something
CBSD_EOF
```
What I did in last commit is basically this:
```
/usr/bin/nice -n 0 /usr/sbin/jexec -U root 2 /bin/sh -c "read something"
```

Now I can run the commands that are interactive and arguments are not removed. These are the commands I tested with:
```
cbsd jexec jname='*' pkg update -f
cbsd jexec jname='*' id
cbsd jexec jname='cbsd' read something
```

@obma as you reported problems with old jexec, can you test this, too?

**Comment by olevole** [comment]
@mekanix this works for me. I do not have poudriere repo, so I tested with:
```
cbsd jexec jname='*' pkg upgrade -r FreeBSD -y
```
Сan you commit your last option please?

**Comment by mekanix** [comment]
It's committed and part of this PR. I can simplify it even more. If `LOGIN_STR` is `/bin/sh` by default, we can have only one `jexec` line and remove check for `LOGIN_STR`. What do you think?

**Comment by olevole** [comment]
@mekanix I'm not sure. LOGIN_STR can be as /bin/bash or qemu-user etc, and not everyone can have an option *-с*

I think string with LOGIN_STR can be as:
```
exec /usr/bin/nice -n ${nice} ${SETFIB} ${CPUSET} ${JEXEC_CMD} -U ${user} ${jid} ${LOGIN_STR} "${cmd}"
```
but I have not tested it

**Comment by mekanix** [comment]
OK, let's fix one thing at the time. Can I merge this PR as it is now?

**Comment by olevole** [comment]
Yes please

**Pull request merged**
