### PR TITLE
Configure myepair for IPv6

### PR DESCRIPTION
**Pull request by mekanix**
I'm not sure this is the right place nor that only epairs need this, so we might explore this further.

### CODE REVIEW

**Comment by olevole** [comment]
@mekanix the ability to configure the interface flags from the CBSD side is interesting (despite the fact that (for VNET jails) it is assumed that the user will do it himself via jail rc.conf ).

But in your case there is no way to regulate this (for example, disable v6 or use other flags).

Something similar was here https://github.com/cbsd/cbsd/issues/540#issuecomment-858649627  where 'sysrc' for jcreate was introduced. However, in your version, we tweak hard code every time we start, without any configuration files.

Perhaps we should add additional customization settings for VNET interfaces? Partially, it will repeat the 'jcreate sysrc' possibilities.

**Comment by mekanix** [comment]
I will have to experiment more and get back to you.

**Comment by mekanix** [comment]
As my problems with IPv6 go beyond CBSD itself, this will take some time. In the mean time if there's a suggestion how to solve [my problems](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261129), please let me know.

**Comment by olevole** [comment]
It will take some time. If your changes help you, I can add a custom parameter to the cbsd for additional vnet interface options ( probably over the next weekend )

**Comment by mekanix** [comment]
For now, just ignore this PR, as I don't know what is causing problems with IPv6. One of the suggestions is to replace rtadvd with dnsmasq, which might come handy for dual stack.

**Pull request closed without merging**
