### PR TITLE
Kill dhclient before jail stop

### PR DESCRIPTION
**Pull request by mekanix**

### CODE REVIEW

**Comment by mekanix** [comment]
Without killing dhclient in the jail, `cbsd jstop` hangs.

**Comment by olevole** [comment]
Just wondering, dhclient doesn't die on /etc/rc.shutdown sequince ( jail stop = sh /etc/rc.shutdown )

**Comment by mekanix** [comment]
Unfortunately it doesn't. As a matter of fact if I don't kill it with -9 it hangs the jail

**Comment by olevole** [comment]
ok

**Pull request merged**
