### PR TITLE
fix validate_jname function and reverse its return value

### PR DESCRIPTION
**Pull request by maxatome**
btw always quote its arg when calling it.

grep regexp changed: remove useless escaping, add ";" as forbidden char and remove "E" as forbidden char.

### CODE REVIEW

**Comment by maxatome** [comment]
Perhaps should we forbid "\" too?

**Comment by olevole** [comment]
it looks reasonable to me

**Comment by olevole** [comment]
> Perhaps should we forbid \ too?

I can not find strict rules for jail name ( in man jail or /usr/src/usr.sbin/jail source ) but in all probability yes, this is a special character.

in fact, I think in large installation we should use some kind of controller  (sample: https://www.bsdstore.ru/en/broker_driven_sample_ssi.html ) over CBSD for mapping between <UID> of jail (or VM name) and the human name of the virtual environment.

E.g, each bhyve/XEN/jail environment created with uid as name:

1,2,3,4 ...

and controller can store map between 
1 - "virtual host 1"
2 - "client 2"
3 - "person 51"

..

Since FreeBSD has certain restrictions on the name for jail or VMM(bhyve)

**Comment by olevole** [comment]
well, 
cat /tmp/a.j :
`
tsd\estjail {
   path = /;
   mount.devfs;
   host.hostname = testhostname;
   exec.start = "/bin/sh /etc/rc";
   exec.stop = "/bin/sh /etc/rc.shutdown jail";
}`

`jail -f /tmp/a.j -c`

leads to an error. So yes, I think we should forbid \ too

**Comment by maxatome** [comment]
It seems it a jail name is be a bit more lax than expected, see:
- unquoted: https://github.com/freebsd/freebsd/blob/master/usr.sbin/jail/jaillex.l#L87
- quoted: https://github.com/freebsd/freebsd/blob/master/usr.sbin/jail/jaillex.l#L95
- double-quoted: https://github.com/freebsd/freebsd/blob/master/usr.sbin/jail/jaillex.l#L99

char escaping handled by [text2lval function](https://github.com/freebsd/freebsd/blob/master/usr.sbin/jail/jaillex.l#L176).

**Comment by maxatome** [comment]
From `man 8 jail`:
```
name    The jail name.  This is an arbitrary string that identifies a
        jail (except it may not contain a ‘.’).
```
From `man 5 jail.conf`:
```
String format
  Parameter values, including jail names, can be single tokens or quoted
  strings.  A token is any sequence of characters that aren't considered
  special in the syntax of the configuration file (such as a semicolon or
  whitespace).  If a value contains anything more than letters, numbers,
  dots, dashes and underscores, it is advisable to put quote marks around
  that value.  Either single or double quotes may be used.

  Special characters may be quoted by preceding them with a backslash.
  Common C-style backslash character codes are also supported, including
  control characters and octal or hex ASCII codes.  A backslash at the end
  of a line will ignore the subsequent newline and continue the string at
  the start of the next line.
```
```

**Comment by olevole** [comment]
Thanks for explanation, I missed the jail.conf man. It seems at the moment CBSD has more stringent name requirements, since we usually don’t quoted ${jname} variables in the code.

**Comment by maxatome** [comment]
I can rework the validation rule to only accept something like `^[a-zA-Z0-9_@%:][-a-zA-Z0-9_@%:]*$` just to avoid `-` as first char (and so no confusion possible with an option when used later).
Other chars `@`, `%` or `:` can appear even ahead without being interpreted by `sh` when not quoted.
Tell me.

**Comment by maxatome** [comment]
Just added a new commit as proposal.

**Comment by olevole** [comment]
@maxatome I can’t check it now in work, but a few remarks:

1) is underscope is valid char with [-a-zA-Z0-9_@%:] ? E.g, 

jail_1, jail_2 - valid names for CBSD (and jail)

2) instead of awk, please use ${AWK_CMD} macros, all external cmd should be as macros ( to increase code portability between DragonFLYBSD, TrueOS .. ) and as an additional check that all the commands in the system are available (this is relevant with the advent of the base-in-pkg)

**Comment by maxatome** [comment]
1. yes it is, you can use the following shell script to test the `validate_jname` function:
   ```sh
   #!/bin/sh
   AWK_CMD=/usr/bin/awk
   . path/to/the/repo/cbsd/nc.subr
   validate_jname "$@" && echo OK
   ```
   then launch it as `./test.sh jail_1` for example.
2. done

**Comment by olevole** [comment]
@maxatome looks good! please merge

**Pull request merged**
